### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by ColeTrammer** [ColeTrammer/iros#20]
# Summary

See the [Iris Kernel development plan](https://github.com/ColeTrammer/iros/blob/iris/docs/iris/design/development_plan.md)

# Progress

- [x] Perform a Context Switch
  - [x] Boot hello world kernel
  - [x] Call C++ global constructors (.init_array + .init)
  - [x] x86_64 IDT
  - [x] x86_64 GDT
  - [x] x86_64 TSS
  - [x] Page frame allocation
  - [x] Page manipulation
  - [x] Heap allocation in kernel space
  - [x] Execute kernel function in ring 3
- [x] Run Userspace Task
  - [x] Task list
  - [x] Virtual memory allocation
  - [x] Cooperative scheduling
  - [x] Record task state and vector number in interrupt handlers
  - [x] Basic executable loading (from limine boot module) 
  - [x] Interrupt controller (x86 PIC)
  - [x] HW timer driver (x86 PIT)
  - [x] Preemptive scheduling
  - [x] File system device driver (initrd)
  - [x] Userspace run time library (libccpp)
  - [x] Executable loading (dynamically from initrd)
  - [X] Print system call and hello world from userspace
- [x] Refactor kernel so far
  - [x] Properly cross compile kernel in the build system
  - [x] Task creation APIs
  - [x] Enable memory protection
  - [x] Enable other security checks (SMAP and SMEP)
  - [x] Move executable loading out of init.cpp
  - [x] Remove excessive print statements throughout the kernel
  - [x] Add more error enumerator values and use them
  - [x] Put architecture specific code inside amd64 directory
- [x] Core kernel improvements
  - [x] #21
  - [x] #22
  - [x] #23
  - [x] #25
  - [x] #27
  - [x] #28
  - [x] #30
  - [x] #31
  - [x] #34
  - [x] #39
  - [x] #52
  - [x] #59
  - [x] #60
  - [x] #62
  - [x] #63
  - [x] #64
  - [x] #66
  - [x] #81
  - [x] #82
  - [x] #83
  - [x] #85
  - [x] #89
  - [x] #95
- [ ] File system
  - [x] #61
  - [x] #102
  - [x] #115
  - [x] #122
  - [x] #124
- [ ] Memory management
  - [ ] #42
  - [x] #106
  - [x] #108
- [ ] Process management
- [ ] Time keeping
- [ ] Dynamic Linking
- [ ] Networking
- [ ] Graphics
- [ ] Audio
- [ ] Synchronization
- [ ] Containerization
- [ ] Di Library improvements
  - [x] #32
  - [ ] #33
  - [x] #51
  - [x] #53
  - [x] #57
  - [x] #71
  - [x] #90
  - [x] #97
  - [x] #100
  - [x] #110
  - [ ] #127
  - [ ] #129
  - [ ] #130
  - [ ] #131
- [ ] Dius Library Improvements
- [ ] Ccpp Library Improvements
  - [x] #112
  - [x] #120
  - [ ] #128
- [x] Project improvements
  - [x] #37
  - [x] #43
  - [x] #45
  - [x] #67
  - [x] #74
  - [x] #78
  - [x] #114
- [ ] Bug fixes
  - [x] #117
  - [ ] #125
